x-base-config: &base-config
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  networks:
    - app_net

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    <<: *base-config

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
    <<: *base-config

  sales-mcp:
    image: sales-mcp
    build:
      context: backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/app:/app/app
    stdin_open: true
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    <<: *base-config


volumes:
  n8n_data:

networks:
  app_net:
    driver: bridge
